sudo: required

addons:
  code_climate:
    repo_token: "$CC"

services:
  - docker

install:
  - docker build -t mayaml .

script:
  - docker run -it --rm -e  -v CODECLIMATE_REPO_TOKEN=$CC  $TRAVIS_BUILD_DIR:/opt/project/code mayaml bundle exec rake

deploy:
  provider: rubygems
  api_key: "$RG"
  on:
    branch: master
    tags: true
